### ISSUE TITLE
What to do if I do not have a NERSC account

### ISSUE THREAD

**Issue by forero** [desihub/tutorials#86]
Add descriptions in the README about what to do if I do not have a NERSC account. i.e. how to use [Datalab](https://datalab.noirlab.edu/)

**Comment by stephjuneau** [comment]
@forero What do you think of also adding a README.md file in the getting_started/ folder? We could even organize the content of the other two .md files there? I'm suggesting this because the top level README.md is very comprehensive therefore a bit on the longer side. I won't implement this to start but if you like the idea, I could work on both the top-level README and suggest a new README in getting_started.

**Comment by forero** [comment]
Having a single README.md in the getting started folder (and integrating the other two .md files there) sounds good. Can you suggest a new README?

**Comment by stephjuneau** [comment]
Yes, let me go ahead and create something and I'll tag you again for review.
